//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "rust", table_name = "food_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: Date,
    pub time: Time,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub weight: f64,
    #[sea_orm(column_type = "Double")]
    pub calories: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
